# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('added_by', models.CharField(blank=True, max_length=200, null=True)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
