# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0003_computer_checked_in_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='checked_out_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
